DO $$
BEGIN
  CREATE TYPE "PromoCodeType" AS ENUM ('DISCOUNT', 'GIFT');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "promo_codes"
  ADD COLUMN IF NOT EXISTS "type" "PromoCodeType" NOT NULL DEFAULT 'DISCOUNT',
  ADD COLUMN IF NOT EXISTS "minOrderAmount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "startsAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "giftName" TEXT,
  ADD COLUMN IF NOT EXISTS "giftImage" TEXT,
  ADD COLUMN IF NOT EXISTS "giftPrice" INTEGER;

ALTER TABLE "orders"
  ADD COLUMN IF NOT EXISTS "appliedPromoType" "PromoCodeType",
  ADD COLUMN IF NOT EXISTS "appliedPromoGiftName" TEXT,
  ADD COLUMN IF NOT EXISTS "appliedPromoGiftImage" TEXT,
  ADD COLUMN IF NOT EXISTS "appliedPromoGiftPrice" INTEGER;
